### ISSUE TITLE
export world to obj file

### ISSUE THREAD

**Issue by andykais** [andykais/minecraft-discord-bot#3]
this is the command for exporting our island

```bash
java -jar /root/minecraft-discord-bot/obj-exporter/jMc2Obj-115.jar --output=/root/obj-output --chunks=-11,-2,-1,9 --height=30,150 --offset=center --texturescale=2 --resourcepack=/root/minecraft-default-texture-pack-1.18/pack.mcmeta /root/minecraft-discord-bot/minecraft-server/world
```

**Comment by andykais** [comment]
```
CHUNKS=11,-2,-1,9:2,-1,-10,9 
HEIGHT=30,150:10:160
```

```yaml
env_vars:
  - DISCORD_BOT_TOKEN
  - CERT
  - CERT_KEY
obj_exports:
  - name: Swag Island
    chunks: { min_x: -11, min_y: -2, max_x: -1, max_y: 9 }
    height: { min: 30, max: 150 }
  - name: James' Forward Base
    chunks: { min_x: -11, min_y: -2, max_x: -1, max_y: 9 }
    height: { min: 30, max: 300 }
```

**Comment by robbiefish** [comment]
```yaml
env_vars:
  - DISCORD_BOT_TOKEN
  - CERT
  - CERT_KEY
worlds:
  - name: Island
    jar: dependencies/minecraft-server/minecraft_server.1.18.jar
    directory: worlds/island
    obj_exports:
      - name: Swag Island
        chunks: { min_x: -11, min_y: -2, max_x: -1, max_y: 9 }
        height: { min: 30, max: 150 }
      - name: James' Forward Base
        chunks: { min_x: -11, min_y: -2, max_x: -1, max_y: 9 }
        height: { min: 30, max: 300 }
```
